image: atlassian/default-image:4

pipelines:
  default:
    - stage:
        name: Test
        steps:
          - step:
              name: Running test script
              image: golang:1.21.5
              script:
                - sh ./scripts/ci/test.sh
  branches:
    main:
      - stage:
          name: Build main
          steps:
            - step:
                size: 2x
                name: Running build script
                caches:
                  - docker
                script:
                  - sh ./scripts/main/build.sh
                services:
                  - docker
  tags:
    "v**.**.**":
      - stage:
          name: Build tag
          steps:
            - step:
                size: 2x
                name: Running build script
                caches:
                  - docker
                script:
                  - sh ./scripts/tags/build.sh
                services:
                  - docker